<?php

declare(strict_types=1);

namespace Oscurlo\ComponentRenderer\Support;

use DOMDocument;
use DOMXPath;
use Tidy;

final class HtmlHelper
{
    /**
     * Attribute added to the <html> tag generated by wrap(), so the library can
     * recognise its own wrapper and never mistake it for a real document.
     */
    public const WRAPPER_MARKER = "data-component-renderer";

    /**
     * A real document starts (ignoring whitespace, comments and doctype) with <html>.
     * The <html> attributes are captured in the "attrs" group.
     */
    private const DOCUMENT_PATTERN = '/^\s*(?:<!--.*?-->\s*)*(?:<!DOCTYPE[^>]*>\s*)?(?:<!--.*?-->\s*)*<html(?<attrs>(?:\s[^>]*)?)>/is';

    /**
     * Generate a minimal HTML document wrapper around a fragment.
     * Used internally so DOMDocument can parse partial HTML reliably.
     *
     * @param  string $html     HTML fragment
     * @param  string $encoding Encoding type
     * @return string
     */
    public static function wrap(
        string $html,
        string $encoding = "UTF-8",
    ): string {
        return <<<HTML
        <html lang="en" data-component-renderer>
            <meta http-equiv="Content-Type" content="text/html;charset={$encoding}">
            <meta charset="{$encoding}">
            <body>{$html}</body>
        </html>
        HTML;
    }

    /**
     * Extract only the inner content of the <body> tag from a full HTML document.
     *
     * @param  string $html     Full HTML document
     * @param  string $version  DOMDocument version
     * @param  string $encoding DOMDocument encoding
     * @return string
     */
    public static function unwrap(
        string $html,
        string $version = "1.0",
        string $encoding = "UTF-8",
    ): string {
        if ($html === "") {
            return "";
        }

        $dom = new DOMDocument($version, $encoding);

        libxml_use_internal_errors(true);
        $dom->loadHTML($html);
        libxml_clear_errors();

        $xpath = new DOMXPath($dom);
        $bodyNode = $xpath->query("//body")->item(0);
        $bodyContent = "";

        if ($bodyNode) {
            foreach ($bodyNode->childNodes as $child) {
                $bodyContent .= $dom->saveHTML($child);
            }
        }

        return $bodyContent !== "" ? $bodyContent : $html;
    }

    /**
     * Check whether the given string is a real, user-provided HTML document:
     * it must start with <html> (optionally preceded by whitespace, comments
     * and a doctype). Markup that merely mentions <html> somewhere inside
     * (a <pre> sample, a script string, a comment) is a fragment, and so is
     * the wrapper generated by wrap().
     *
     * @param  string $html
     * @return bool
     */
    public static function isDocument(string $html): bool
    {
        return self::matchDocument($html, $attrs) && !self::hasMarker($attrs);
    }

    /**
     * Check whether the given string is the wrapper generated by wrap().
     *
     * @param  string $html
     * @return bool
     */
    public static function isWrapped(string $html): bool
    {
        return self::matchDocument($html, $attrs) && self::hasMarker($attrs);
    }

    /**
     * Remove the wrapper generated by wrap(), working on the raw string.
     * Unlike unwrap(), it never goes through DOMDocument, so the case of custom
     * tags (e.g. <MyTag>) is preserved. Non-wrapped input is returned as-is.
     *
     * @param  string $html
     * @return string
     */
    public static function stripWrapper(string $html): string
    {
        if (!self::isWrapped($html)) {
            return $html;
        }

        $start = stripos($html, "<body>");
        $end = strripos($html, "</body>");

        if ($start === false || $end === false || $end < $start) {
            return $html;
        }

        return substr($html, $start + 6, $end - $start - 6);
    }

    /**
     * @param  string      $html
     * @param  string|null $attrs Raw attributes of the <html> tag, set when it matches
     * @return bool
     */
    private static function matchDocument(string $html, ?string &$attrs = null): bool
    {
        if (preg_match(self::DOCUMENT_PATTERN, $html, $match) !== 1) {
            $attrs = "";
            return false;
        }

        $attrs = $match["attrs"];

        return true;
    }

    private static function hasMarker(string $attrs): bool
    {
        $marker = preg_quote(self::WRAPPER_MARKER, "/");

        return preg_match("/\\s{$marker}(?=[\\s=\\/]|$)/i", $attrs) === 1;
    }

    /**
     * Tidy the given HTML string using the Tidy extension.
     *
     * @param  string $html
     * @param  array $options
     * @return string
     */
    public static function tidy(string $html, array $options = []): string
    {
        if (!extension_loaded("tidy")) {
            return $html;
        }

        // Lo formateo como lo hace mi editor a 4 espacios
        $defaultOptions = [
            "indent" => true,
            "indent-spaces" => 4,
            "wrap" => 0,
            "logical-emphasis" => false,
            "drop-empty-elements" => false,
        ];

        $tidy = new Tidy();
        $tidy->parseString($html, $defaultOptions + $options);
        $tidy->cleanRepair();

        return $tidy->value;
    }
}
